<?php

namespace Database\Seeders;
use Iluminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class EventosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $today = "2024-07-12";
        
        DB::table("eventos")->insert([
            ["id"=>1,"titulo"=>"Rosse","descripcion"=>"Vive la fiesta con Rosse, las mejores canciones del momento","qr"=>"","precio"=>20.99,"fecha_inicio"=>"2024-06-01","fecha_fin"=>"2024-06-01","foto"=>"https://festgra.com/wp-content/uploads/2019/11/rosse-vip-club-malaga-discoteca-fiesta-grande-.jpg","localizacion"=>"Cmo de S. Rafael, 93, Carretera de Cádiz, 29006 Málaga","latitud"=>-4.452977837449125,"longitud"=>36.705325241571266,"valoracion"=>2,"boost"=>"Rosse","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>2,"titulo"=>"K2","descripcion"=>"Fiesta, musica, alcohol y mucha diversion, ¿Piensas perderte esta experiencia?","qr"=>"","precio"=>15.60,"fecha_inicio"=>"2024-07-10","fecha_fin"=>"2024-07-10","foto"=>"https://www.despedidastemptation.com/wp-content/uploads/las-mejores-discotecas-de-malaga-discoteca-k2-malaga.jpeg","localizacion"=>"Av. de Isaac Peral, 43, Carretera de Cádiz, 29004 Málaga","latitud"=>-4.45980,"longitud"=>36.69199,"valoracion"=>4,"boost"=>"K2","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>3,"titulo"=>"Jaleo","descripcion"=>"","qr"=>"","precio"=>10.00,"fecha_inicio"=>"2024-08-20","fecha_fin"=>"2024-08-25","foto"=>"https://www.malagasesale.com/wp-content/uploads/118829019_1161885664194724_8206743658028533995_n.jpg","localizacion"=>"","latitud"=>-4.467372525282044,"longitud"=>36.7206645409886,"valoracion"=>3,"boost"=>"Jaleo SL","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>4,"titulo"=>"Reggaeton Beach Festival","descripcion"=>"","qr"=>"","precio"=>25.9,"fecha_inicio"=>"2024-09-15","fecha_fin"=>"2024-09-20","foto"=>"https://estaticos.esmadrid.com/cdn/farfuture/QolHHrrdfMkVx4nFCXdEi-ubWooDOs5CDOhPiFNXKGw/mtime:1700572835/sites/default/files/eventos/eventos/reggaeton_beach_festival_1.jpg","localizacion"=>"Playa Playazo Rio Seco, Nerja.","latitud"=>-3.899700635574178,"longitud"=>36.743705673722474,"valoracion"=>5,"boost"=>"Ayuntamiento de Nerja","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>5,"titulo"=>"Puro Latino","descripcion"=>"Con el invitado especial Chirs como DJ en esta sesión de musica, con un ambiente insuperable y todo lo que te imaginas, estamos preparados para la fiesta.","qr"=>"","precio"=>25.90,"fecha_inicio"=>"2024-06-19","fecha_fin"=>"2024-06-20","foto"=>"https://www.diariodecadiz.es/2023/10/05/noticias-provincia-cadiz/imagen-edicion-Puro-Latino-Puerto_1836126899_194089312_667x375.jpg","localizacion"=>"","latitud"=>-4.513778091549178,"longitud"=>36.62069832234932,"valoracion"=>3,"boost"=>"Ayuntamiento de Nerja","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>6,"titulo"=>"Concierto Sergio Dalma","descripcion"=>"","qr"=>"","precio"=>60.50,"fecha_inicio"=>"2024-06-28","fecha_fin"=>"2024-06-28","foto"=>"https://cdn-p.smehost.net/sites/ac8769d0b5a24f4caa78aab9d5fa4c47/wp-content/uploads/2023/11/Web-baja.jpg","localizacion"=>"Auditorio Municipal Cortijo de Torres, C. Paquiro, 9 Málaga","latitud"=>-4.467003353505538,"longitud"=>36.698957703793404,"valoracion"=>5,"boost"=>"Eternidad Producciones AIE. - V0169968","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>7,"titulo"=>"QUEENS OF THE STONE AGE","descripcion"=>"Queens of the Stone Age, la mítica banda de rock aclamada a nivel mundial, hará parada en Fuengirola dentro de su extensa gira internacional. Con su inconfundible sonido y una carrera musical repleta de éxitos, el próximo 23 de Junio de 2024, el grupo liderado por Josh Hommes desembarcará en la ciudad malagueña con su imponente y enérgico directo, además, no estarán solos, pues estarán acompañados por una banda telonera aún por desvelar pero que promete una gran sorpresa. ","qr"=>"","precio"=>55.00,"fecha_inicio"=>"2024-06-23","fecha_fin"=>"2024-06-23","foto"=>"https://dynamicmedia.livenationinternational.com/a/w/m/08a8b2b6-ccff-4af5-8b46-c2dad7ac1a97.jpg","localizacion"=>"Marenostrum fuengirola","latitud"=>-4.629283998715305,"longitud"=>36.523582965453144,"valoracion"=>4,"boost"=>"Ayuntamiento de fuengirola","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            ["id"=>8,"titulo"=>"Concierto Rozalén","descripcion"=>"Rozalen viene a Málaga para ofrecernos un concierto inolvidable","qr"=>"","precio"=>49.50,"fecha_inicio"=>"2024-06-15","fecha_fin"=>"2024-06-15","foto"=>"https://malagadecultura.com/wp-content/uploads/2023/12/Rozalen.jpg","localizacion"=>"Plaza de Toros de la Malagueta, P.º Reding, 20, Málaga-Este, 29016 Málaga","latitud"=>-4.410775949056343,"longitud"=>36.720365398572675,"valoracion"=>3,"boost"=>"","created_at"=>date('Y-m-d h:i:m'),"updated_at"=>date('Y-m-d h:i:m')],
            [
                "id" => 9,
                "titulo"=>"Juanes",
                "descripcion"=>"Con 4 Grammys guardados en una maleta junto con millones de éxitos mundiales desde la Camisa Negra hasta A Dios le Pido o Nada Valgo sin tu Amor, aterriza Juanes en Málaga el próximo 30 de junio para ponerle su melodía única a una velada de verano que va a ser inolvidable.",
                "qr"=>"",
                "precio"=>42.50,
                "fecha_inicio"=>"2024-06-30",
                "fecha_fin"=>"2024-06-30",
                "foto"=>"https://mmalaga.es/wp-content/uploads/2024/03/juanes.jpg",
                "localizacion"=>"Málaga Forum",
                "latitud"=>-4.487509593922004,
                "longitud"=>36.69115055913355,
                "valoracion"=>4,
                "boost"=>"Yamaha",
                "created_at"=>NOW(),
                "updated_at"=>NOW()
            ],
            [
                "id"=>10,
                "titulo"=>"India Martínez",
                "descripcion"=>"Compra tus entradas para el evento de India Martínez que se va a celebrar en el Auditorio Municipal de Cortijo de Torres.",
                "qr"=>"",
                "precio"=>38.50,
                "fecha_inicio"=>"2024-06-15",
                "fecha_fin"=>"2024-06-15",
                "foto"=>"https://d2cyzdatssrhg7.cloudfront.net/export/sites/default/ets/.content/products/img/00-000894F.jpg?__locale=es",
                "localizacion"=>"Auditorio Municipal Cortijo de Torres",
                "latitud"=>-4.466977771960777,
                "longitud"=>36.698947085147076,
                "valoracion"=>3,
                "boost"=>"Eternidad Producciones AIE - V01699685",
                "created_at"=>NOW(),
                "updated_at"=>NOW()
            ],
            [
                "id"=>11,
                "titulo"=>"NO TE VA GUSTAR",
                "descripcion"=>"La banda uruguaya No Te Va Gustar celebra su historia en canciones con una amplia gira internacional que no solo será un reencuentro con su público sino que promete ser un hito en su trayectoria. En tres décadas, desde aquella primera presentación en una fría madrugada montevideana de 1994 en la Plaza Alto Perú, hasta los conciertos actuales para cientos de miles de asistentes, mucho ha cambiado el mundo; desde la forma en que nos comunicamos hasta la manera en que producimos y consumimos música.",
                "qr"=>"",
                "precio"=>32.00,
                "fecha_inicio"=>"2024-06-28",
                "fecha_fin"=>"2024-06-28",
                "foto"=>"https://www.teatrocervantes.com/public/images/content/espectaculos/896/af8795cb08d2402575daac782293b1d5.jpg?t=665385b16c742",
                "localizacion"=>"TEATRO CERVANTES Málaga",
                "latitud"=>36.724776593669006,
                "longitud"=>-4.418625518174503,
                "valoracion"=>5,
                "boost"=>"Ayuntamiento de malaga - MalagaProcultura",
                "created_at"=>NOW(),
                "updated_at"=>NOW()
            ],
                
                    [
                        "id"=>12,
                        "titulo" => "Concierto Rock",
                        "descripcion" => "Concierto de rock con varias bandas",
                        "qr" => "QR1234567890",
                        "precio" => 55.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "concierto_rock.jpg",
                        "localizacion" => "Auditorio Nacional",
                        "latitud" => 40.45,
                        "longitud" => -3.7,
                        "valoracion" => 5,
                        "boost" => "boost123",
                        "created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>13,
                        "titulo" => "Feria del Libro",
                        "descripcion" => "Feria con presencia de autores y editoriales",
                        "qr" => "QR1234567891",
                        "precio" => 35.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "feria_libro.jpg",
                        "localizacion" => "Parque Central",
                        "latitud" => 40.42,
                        "longitud" => -3.7,
                        "valoracion" => 4,
                        "boost" => "boost124",
                        "created_at"=>NOW(),
                "updated_at"=>NOW()
                    ],
                    [
                        "id"=>14,
                        "titulo" => "Festival de Jazz",
                        "descripcion" => "Festival de Jazz con artistas internacionales",
                        "qr" => "QR1234567892",
                        "precio" => 45.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_jazz.jpg",
                        "localizacion" => "Teatro Real",
                        "latitud" => 40.42,
                        "longitud" => -3.71,
                        "valoracion" => 5,
                        "boost" => "boost125",
                        "created_at"=>NOW(),
                "updated_at"=>NOW()
                    ],
                    [
                        "id"=>15,
                        "titulo" => "Exposición de Arte Moderno",
                        "descripcion" => "Exposición de obras de arte moderno",
                        "qr" => "QR1234567893",
                        "precio" => 25.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "expo_arte_moderno.jpg",
                        "localizacion" => "Museo de Arte Moderno",
                        "latitud" => 40.43,
                        "longitud" => -3.72,
                        "valoracion" => 4,
                        "boost" => "boost126",
                        "created_at"=>NOW(),
                "updated_at"=>NOW()
                    ],
                    [
                        "id"=>16,
                        "titulo" => "Teatro Clásico",
                        "descripcion" => "Representación de una obra de teatro clásico",
                        "qr" => "QR1234567894",
                        "precio" => 50.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "teatro_clasico.jpg",
                        "localizacion" => "Teatro Español",
                        "latitud" => 40.44,
                        "longitud" => -3.73,
                        "valoracion" => 5,
                        "boost" => "boost127","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>17,
                        "titulo" => "Festival de Cine",
                        "descripcion" => "Festival de cine con proyecciones y premios",
                        "qr" => "QR1234567895",
                        "precio" => 30.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_cine.jpg",
                        "localizacion" => "Cine Capitol",
                        "latitud" => 40.45,
                        "longitud" => -3.74,
                        "valoracion" => 4,
                        "boost" => "boost128","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>18,
                        "titulo" => "Concierto de Pop",
                        "descripcion" => "Concierto de pop con artistas del momento",
                        "qr" => "QR1234567896",
                        "precio" => 55.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "concierto_pop.jpg",
                        "localizacion" => "Wanda Metropolitano",
                        "latitud" => 40.46,
                        "longitud" => -3.75,
                        "valoracion" => 5,
                        "boost" => "boost129","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>19,
                        "titulo" => "Feria de Gastronomía",
                        "descripcion" => "Feria con los mejores chefs y degustaciones",
                        "qr" => "QR1234567897",
                        "precio" => 35.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "feria_gastronomia.jpg",
                        "localizacion" => "Palacio de Congresos",
                        "latitud" => 40.47,
                        "longitud" => -3.76,
                        "valoracion" => 4,
                        "boost" => "boost130","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>20,
                        "titulo" => "Festival de Música Clásica",
                        "descripcion" => "Festival con las mejores orquestas de música clásica",
                        "qr" => "QR1234567898",
                        "precio" => 45.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_musica_clasica.jpg",
                        "localizacion" => "Auditorio Nacional",
                        "latitud" => 40.48,
                        "longitud" => -3.77,
                        "valoracion" => 5,
                        "boost" => "boost131","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>21,
                        "titulo" => "Exposición Fotográfica",
                        "descripcion" => "Exposición de fotografías de artistas contemporáneos",
                        "qr" => "QR1234567899",
                        "precio" => 25.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "expo_fotografia.jpg",
                        "localizacion" => "Galería de Arte",
                        "latitud" => 40.49,
                        "longitud" => -3.78,
                        "valoracion" => 4,
                        "boost" => "boost132","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>22,
                        "titulo" => "Festival de Danza",
                        "descripcion" => "Festival de danza con actuaciones de diferentes estilos",
                        "qr" => "QR1234567900",
                        "precio" => 50.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_danza.jpg",
                        "localizacion" => "Teatro Real",
                        "latitud" => 40.50,
                        "longitud" => -3.79,
                        "valoracion" => 5,
                        "boost" => "boost133","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>23,
                        "titulo" => "Conferencia de Tecnología",
                        "descripcion" => "Conferencia sobre las últimas tendencias en tecnología",
                        "qr" => "QR1234567901",
                        "precio" => 30.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "conferencia_tecnologia.jpg",
                        "localizacion" => "Centro de Convenciones",
                        "latitud" => 40.51,
                        "longitud" => -3.80,
                        "valoracion" => 4,
                        "boost" => "boost134","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>24,
                        "titulo" => "Torneo de eSports",
                        "descripcion" => "Torneo de eSports con los mejores equipos",
                        "qr" => "QR1234567902",
                        "precio" => 55.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "torneo_esports.jpg",
                        "localizacion" => "Pabellón Deportivo",
                        "latitud" => 40.52,
                        "longitud" => -3.81,
                        "valoracion" => 5,
                        "boost" => "boost135","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>25,
                        "titulo" => "Festival de Verano",
                        "descripcion" => "Festival de verano con actividades al aire libre",
                        "qr" => "QR1234567903",
                        "precio" => 35.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_verano.jpg",
                        "localizacion" => "Parque Central",
                        "latitud" => 40.53,
                        "longitud" => -3.82,
                        "valoracion" => 4,
                        "boost" => "boost136","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>26,
                        "titulo" => "Exposición de Escultura",
                        "descripcion" => "Exposición de esculturas de artistas reconocidos",
                        "qr" => "QR1234567904",
                        "precio" => 25.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "expo_escultura.jpg",
                        "localizacion" => "Museo de Escultura",
                        "latitud" => 40.54,
                        "longitud" => -3.83,
                        "valoracion" => 4,
                        "boost" => "boost137","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>27,
                        "titulo" => "Feria de Automóviles",
                        "descripcion" => "Feria con las últimas novedades del mundo del automóvil",
                        "qr" => "QR1234567905",
                        "precio" => 45.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "feria_automoviles.jpg",
                        "localizacion" => "Centro de Exposiciones",
                        "latitud" => 40.55,
                        "longitud" => -3.84,
                        "valoracion" => 5,
                        "boost" => "boost138","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>28,
                        "titulo" => "Concierto de Música Indie",
                        "descripcion" => "Concierto con las mejores bandas de música indie",
                        "qr" => "QR1234567906",
                        "precio" => 50.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "concierto_indie.jpg",
                        "localizacion" => "Plaza Mayor",
                        "latitud" => 40.56,
                        "longitud" => -3.85,
                        "valoracion" => 5,
                        "boost" => "boost139","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>29,
                        "titulo" => "Festival de Teatro",
                        "descripcion" => "Festival con las mejores obras de teatro",
                        "qr" => "QR1234567907",
                        "precio" => 30.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_teatro.jpg",
                        "localizacion" => "Teatro Nacional",
                        "latitud" => 40.57,
                        "longitud" => -3.86,
                        "valoracion" => 4,
                        "boost" => "boost140","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>30,
                        "titulo" => "Exposición de Pintura",
                        "descripcion" => "Exposición de pinturas de artistas locales",
                        "qr" => "QR1234567908",
                        "precio" => 25.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "expo_pintura.jpg",
                        "localizacion" => "Galería Local",
                        "latitud" => 40.58,
                        "longitud" => -3.87,
                        "valoracion" => 4,
                        "boost" => "boost141","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>31,
                        "titulo" => "Concierto de Música Electrónica",
                        "descripcion" => "Concierto con los mejores DJs de música electrónica",
                        "qr" => "QR1234567909",
                        "precio" => 55.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "concierto_electronica.jpg",
                        "localizacion" => "Estadio Olímpico",
                        "latitud" => 40.59,
                        "longitud" => -3.88,
                        "valoracion" => 5,
                        "boost" => "boost142","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>32,
                        "titulo" => "Feria de Artesanía",
                        "descripcion" => "Feria con productos de artesanía de diferentes regiones",
                        "qr" => "QR1234567910",
                        "precio" => 35.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "feria_artesania.jpg",
                        "localizacion" => "Centro Histórico",
                        "latitud" => 40.60,
                        "longitud" => -3.89,
                        "valoracion" => 4,
                        "boost" => "boost143","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>33,
                        "titulo" => "Festival de Ópera",
                        "descripcion" => "Festival con las mejores voces de la ópera mundial",
                        "qr" => "QR1234567911",
                        "precio" => 45.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_opera.jpg",
                        "localizacion" => "Teatro Real",
                        "latitud" => 40.61,
                        "longitud" => -3.90,
                        "valoracion" => 5,
                        "boost" => "boost144","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>34,
                        "titulo" => "Conferencia de Medicina",
                        "descripcion" => "Conferencia sobre avances en medicina",
                        "qr" => "QR1234567912",
                        "precio" => 30.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "conferencia_medicina.jpg",
                        "localizacion" => "Centro de Convenciones",
                        "latitud" => 40.62,
                        "longitud" => -3.91,
                        "valoracion" => 4,
                        "boost" => "boost145","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>35,
                        "titulo" => "Concierto de Jazz Fusión",
                        "descripcion" => "Concierto con bandas de jazz fusión",
                        "qr" => "QR1234567913",
                        "precio" => 55.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "concierto_jazz_fusion.jpg",
                        "localizacion" => "Sala de Conciertos",
                        "latitud" => 40.63,
                        "longitud" => -3.92,
                        "valoracion" => 5,
                        "boost" => "boost146","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>36,
                        "titulo" => "Festival de Música Folk",
                        "descripcion" => "Festival con las mejores bandas de música folk",
                        "qr" => "QR1234567914",
                        "precio" => 35.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "festival_folk.jpg",
                        "localizacion" => "Parque Regional",
                        "latitud" => 40.64,
                        "longitud" => -3.93,
                        "valoracion" => 4,
                        "boost" => "boost147","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ],
                    [
                        "id"=>37,
                        "titulo" => "Exposición de Fotografía",
                        "descripcion" => "Exposición de fotografía de autor",
                        "qr" => "QR1234567915",
                        "precio" => 25.00,
                        "fecha_inicio" => $today,
                        "fecha_fin" => $today,
                        "foto" => "expo_fotografia_autor.jpg",
                        "localizacion" => "Galería de Arte",
                        "latitud" => 40.65,
                        "longitud" => -3.94,
                        "valoracion" => 4,
                        "boost" => "boost148","created_at"=>NOW(),
                        "updated_at"=>NOW()
                    ]
                
        ]);
    }
}