<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class EventoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $today = "2024-01-01";

        DB::table("eventos")->insert([
            [
                "titulo" => "Concierto Rock",
                "descripcion" => "Concierto de rock con varias bandas",
                "qr" => "QR1234567890",
                "precio" => 55.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "concierto_rock.jpg",
                "localizacion" => "Auditorio Nacional",
                "latitud" => 40.45,
                "longitud" => -3.7,
                "valoracion" => 5,
                "boost" => "boost123"
            ],
            [
                "titulo" => "Feria del Libro",
                "descripcion" => "Feria con presencia de autores y editoriales",
                "qr" => "QR1234567891",
                "precio" => 35.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "feria_libro.jpg",
                "localizacion" => "Parque Central",
                "latitud" => 40.42,
                "longitud" => -3.7,
                "valoracion" => 4,
                "boost" => "boost124"
            ],
            [
                "titulo" => "Festival de Jazz",
                "descripcion" => "Festival de Jazz con artistas internacionales",
                "qr" => "QR1234567892",
                "precio" => 45.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_jazz.jpg",
                "localizacion" => "Teatro Real",
                "latitud" => 40.42,
                "longitud" => -3.71,
                "valoracion" => 5,
                "boost" => "boost125"
            ],
            [
                "titulo" => "Exposición de Arte Moderno",
                "descripcion" => "Exposición de obras de arte moderno",
                "qr" => "QR1234567893",
                "precio" => 25.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "expo_arte_moderno.jpg",
                "localizacion" => "Museo de Arte Moderno",
                "latitud" => 40.43,
                "longitud" => -3.72,
                "valoracion" => 4,
                "boost" => "boost126"
            ],
            [
                "titulo" => "Teatro Clásico",
                "descripcion" => "Representación de una obra de teatro clásico",
                "qr" => "QR1234567894",
                "precio" => 50.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "teatro_clasico.jpg",
                "localizacion" => "Teatro Español",
                "latitud" => 40.44,
                "longitud" => -3.73,
                "valoracion" => 5,
                "boost" => "boost127"
            ],
            [
                "titulo" => "Festival de Cine",
                "descripcion" => "Festival de cine con proyecciones y premios",
                "qr" => "QR1234567895",
                "precio" => 30.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_cine.jpg",
                "localizacion" => "Cine Capitol",
                "latitud" => 40.45,
                "longitud" => -3.74,
                "valoracion" => 4,
                "boost" => "boost128"
            ],
            [
                "titulo" => "Concierto de Pop",
                "descripcion" => "Concierto de pop con artistas del momento",
                "qr" => "QR1234567896",
                "precio" => 55.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "concierto_pop.jpg",
                "localizacion" => "Wanda Metropolitano",
                "latitud" => 40.46,
                "longitud" => -3.75,
                "valoracion" => 5,
                "boost" => "boost129"
            ],
            [
                "titulo" => "Feria de Gastronomía",
                "descripcion" => "Feria con los mejores chefs y degustaciones",
                "qr" => "QR1234567897",
                "precio" => 35.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "feria_gastronomia.jpg",
                "localizacion" => "Palacio de Congresos",
                "latitud" => 40.47,
                "longitud" => -3.76,
                "valoracion" => 4,
                "boost" => "boost130"
            ],
            [
                "titulo" => "Festival de Música Clásica",
                "descripcion" => "Festival con las mejores orquestas de música clásica",
                "qr" => "QR1234567898",
                "precio" => 45.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_musica_clasica.jpg",
                "localizacion" => "Auditorio Nacional",
                "latitud" => 40.48,
                "longitud" => -3.77,
                "valoracion" => 5,
                "boost" => "boost131"
            ],
            [
                "titulo" => "Exposición Fotográfica",
                "descripcion" => "Exposición de fotografías de artistas contemporáneos",
                "qr" => "QR1234567899",
                "precio" => 25.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "expo_fotografia.jpg",
                "localizacion" => "Galería de Arte",
                "latitud" => 40.49,
                "longitud" => -3.78,
                "valoracion" => 4,
                "boost" => "boost132"
            ],
            [
                "titulo" => "Festival de Danza",
                "descripcion" => "Festival de danza con actuaciones de diferentes estilos",
                "qr" => "QR1234567900",
                "precio" => 50.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_danza.jpg",
                "localizacion" => "Teatro Real",
                "latitud" => 40.50,
                "longitud" => -3.79,
                "valoracion" => 5,
                "boost" => "boost133"
            ],
            [
                "titulo" => "Conferencia de Tecnología",
                "descripcion" => "Conferencia sobre las últimas tendencias en tecnología",
                "qr" => "QR1234567901",
                "precio" => 30.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "conferencia_tecnologia.jpg",
                "localizacion" => "Centro de Convenciones",
                "latitud" => 40.51,
                "longitud" => -3.80,
                "valoracion" => 4,
                "boost" => "boost134"
            ],
            [
                "titulo" => "Torneo de eSports",
                "descripcion" => "Torneo de eSports con los mejores equipos",
                "qr" => "QR1234567902",
                "precio" => 55.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "torneo_esports.jpg",
                "localizacion" => "Pabellón Deportivo",
                "latitud" => 40.52,
                "longitud" => -3.81,
                "valoracion" => 5,
                "boost" => "boost135"
            ],
            [
                "titulo" => "Festival de Verano",
                "descripcion" => "Festival de verano con actividades al aire libre",
                "qr" => "QR1234567903",
                "precio" => 35.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_verano.jpg",
                "localizacion" => "Parque Central",
                "latitud" => 40.53,
                "longitud" => -3.82,
                "valoracion" => 4,
                "boost" => "boost136"
            ],
            [
                "titulo" => "Exposición de Escultura",
                "descripcion" => "Exposición de esculturas de artistas reconocidos",
                "qr" => "QR1234567904",
                "precio" => 25.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "expo_escultura.jpg",
                "localizacion" => "Museo de Escultura",
                "latitud" => 40.54,
                "longitud" => -3.83,
                "valoracion" => 4,
                "boost" => "boost137"
            ],
            [
                "titulo" => "Feria de Automóviles",
                "descripcion" => "Feria con las últimas novedades del mundo del automóvil",
                "qr" => "QR1234567905",
                "precio" => 45.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "feria_automoviles.jpg",
                "localizacion" => "Centro de Exposiciones",
                "latitud" => 40.55,
                "longitud" => -3.84,
                "valoracion" => 5,
                "boost" => "boost138"
            ],
            [
                "titulo" => "Concierto de Música Indie",
                "descripcion" => "Concierto con las mejores bandas de música indie",
                "qr" => "QR1234567906",
                "precio" => 50.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "concierto_indie.jpg",
                "localizacion" => "Plaza Mayor",
                "latitud" => 40.56,
                "longitud" => -3.85,
                "valoracion" => 5,
                "boost" => "boost139"
            ],
            [
                "titulo" => "Festival de Teatro",
                "descripcion" => "Festival con las mejores obras de teatro",
                "qr" => "QR1234567907",
                "precio" => 30.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_teatro.jpg",
                "localizacion" => "Teatro Nacional",
                "latitud" => 40.57,
                "longitud" => -3.86,
                "valoracion" => 4,
                "boost" => "boost140"
            ],
            [
                "titulo" => "Exposición de Pintura",
                "descripcion" => "Exposición de pinturas de artistas locales",
                "qr" => "QR1234567908",
                "precio" => 25.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "expo_pintura.jpg",
                "localizacion" => "Galería Local",
                "latitud" => 40.58,
                "longitud" => -3.87,
                "valoracion" => 4,
                "boost" => "boost141"
            ],
            [
                "titulo" => "Concierto de Música Electrónica",
                "descripcion" => "Concierto con los mejores DJs de música electrónica",
                "qr" => "QR1234567909",
                "precio" => 55.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "concierto_electronica.jpg",
                "localizacion" => "Estadio Olímpico",
                "latitud" => 40.59,
                "longitud" => -3.88,
                "valoracion" => 5,
                "boost" => "boost142"
            ],
            [
                "titulo" => "Feria de Artesanía",
                "descripcion" => "Feria con productos de artesanía de diferentes regiones",
                "qr" => "QR1234567910",
                "precio" => 35.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "feria_artesania.jpg",
                "localizacion" => "Centro Histórico",
                "latitud" => 40.60,
                "longitud" => -3.89,
                "valoracion" => 4,
                "boost" => "boost143"
            ],
            [
                "titulo" => "Festival de Ópera",
                "descripcion" => "Festival con las mejores voces de la ópera mundial",
                "qr" => "QR1234567911",
                "precio" => 45.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_opera.jpg",
                "localizacion" => "Teatro Real",
                "latitud" => 40.61,
                "longitud" => -3.90,
                "valoracion" => 5,
                "boost" => "boost144"
            ],
            [
                "titulo" => "Conferencia de Medicina",
                "descripcion" => "Conferencia sobre avances en medicina",
                "qr" => "QR1234567912",
                "precio" => 30.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "conferencia_medicina.jpg",
                "localizacion" => "Centro de Convenciones",
                "latitud" => 40.62,
                "longitud" => -3.91,
                "valoracion" => 4,
                "boost" => "boost145"
            ],
            [
                "titulo" => "Concierto de Jazz Fusión",
                "descripcion" => "Concierto con bandas de jazz fusión",
                "qr" => "QR1234567913",
                "precio" => 55.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "concierto_jazz_fusion.jpg",
                "localizacion" => "Sala de Conciertos",
                "latitud" => 40.63,
                "longitud" => -3.92,
                "valoracion" => 5,
                "boost" => "boost146"
            ],
            [
                "titulo" => "Festival de Música Folk",
                "descripcion" => "Festival con las mejores bandas de música folk",
                "qr" => "QR1234567914",
                "precio" => 35.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "festival_folk.jpg",
                "localizacion" => "Parque Regional",
                "latitud" => 40.64,
                "longitud" => -3.93,
                "valoracion" => 4,
                "boost" => "boost147"
            ],
            [
                "titulo" => "Exposición de Fotografía",
                "descripcion" => "Exposición de fotografía de autor",
                "qr" => "QR1234567915",
                "precio" => 25.00,
                "fecha_inicio" => $today,
                "fecha_fin" => $today,
                "foto" => "expo_fotografia_autor.jpg",
                "localizacion" => "Galería de Arte",
                "latitud" => 40.65,
                "longitud" => -3.94,
                "valoracion" => 4,
                "boost" => "boost148"
            ]
        ]);
    }
}